PORT: 8080
COMPATIBILITY:
  - "last 2 versions"
PATHS:
  dist: "dist"
  sass:
    - "src/sass"
    - "bower_components/materialize/sass"
  javascript:
    - "bower_components/jquery/dist/jquery.js"
    - "bower_components/materialize/js/animation.js"
    - "bower_components/materialize/js/buttons.js"
    - "bower_components/materialize/js/cards.js"
    - "bower_components/materialize/js/carousel.js"
    - "bower_components/materialize/js/character_counter.js"
    - "bower_components/materialize/js/chips.js"
    - "bower_components/materialize/js/collapsible.js"
    - "bower_components/materialize/js/dropdown.js"
    - "bower_components/materialize/js/forms.js"
    - "bower_components/materialize/js/global.js"
    - "bower_components/materialize/js/hammer.min.js"
    - "bower_components/materialize/js/initial.js"
    - "bower_components/materialize/js/jquery.easing.1.3.js"
    - "bower_components/materialize/js/jquery.hammer.js"
    - "bower_components/materialize/js/jquery.timeago.min.js"
    - "bower_components/materialize/js/materialbox.js"
    - "bower_components/materialize/js/modal.js"
    - "bower_components/materialize/js/parallax.js"
    - "bower_components/materialize/js/pushpin.js"
    - "bower_components/materialize/js/scrollFire.js"
    - "bower_components/materialize/js/scrollspy.js"
    - "bower_components/materialize/js/sideNav.js"
    - "bower_components/materialize/js/slider.js"
    - "bower_components/materialize/js/tabs.js"
    - "bower_components/materialize/js/tapTarget.js"
    - "bower_components/materialize/js/toasts.js"
    - "bower_components/materialize/js/tooltip.js"
    - "bower_components/materialize/js/transitions.js"
    - "bower_components/materialize/js/velocity.min.js"
    - "bower_components/materialize/js/waves.js"
    - "src/js"
